routes/web.php
<?php

use App\Http\Controllers\ProductController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\VendorController;
use App\Http\Middleware\RedirectIfAuthenticated;
//use SebastianBergmann\CodeCoverage\Report\Html\Dashboard;

//admin dashboard

Route::middleware(['auth','role:admin'])->group(function(){
    Route::get('/admin/dashboard',[AdminController::class,'adminDashbord'])->name('admin.Dashboard');

    Route::get('/admin/logout',[AdminController::class,'adminDestroy'])->name('admin.logout');

    Route::get('/admin/profile',[AdminController::class,'adminProfile'])->name('admin.profile');
    Route::post('/admin/profile/store', [AdminController::class, 'AdminProfileStore'])->name('admin.profile.store');
    Route::get('/admin/change/password', [AdminController::class, 'AdminChangePassword'])->name('admin.change.password');

    Route::post('/admin/update/password', [AdminController::class, 'AdminUpdatePassword'])->name('update.password');

    Route::resource('products',ProductController::class);
    Route::get('/product/inactive/{id}',[ProductController::class,'ProductInactive'])->name('product.inactive');
    Route::get('/product/active/{id}',[ProductController::class,'ProductActive'])->name('product.active');
    Route::resource('brands',BrandController::class);
    Route::resource('categories',CategoryController::class);
});

Route::get('/admin/login',[AdminController::class,'AdminLogin'])->middleware(RedirectIfAuthenticated::class);

Route::get('/vendor/login',[AdminController::class,'VendorLogin'])->middleware(RedirectIfAuthenticated::class);

//vendor dashboard
Route::middleware(['auth','role:vendor'])->group(function(){
    Route::get('/vendor/dashboard',[VendorController::class,'vendorDashbord'])->name('vendor.Dashboard');

    Route::get('/vendor/logout',[AdminController::class,'vendorDestroy'])->name('vendor.logout');

});





Route::get('/', function () {
    return view('frontend.index');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

app/Models/Brand.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    use HasFactory;

    protected $guarded = [];
}

app/Http/Controllers/BrandController.php
<?php

namespace App\Http\Controllers;

use App\Models\Brand;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Image;
class BrandController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $brands = Brand::latest()->get();
        return view('admin.brands.index',compact('brands'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('admin.brands.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {

        Brand::create([
        'brand_name'=>$request->brand_name,
        'brand_slug'=>strtolower(str_replace('','_',$request->brand_name)),
        'brand_image'=> $this->uploadImage(request()->file('brand_image')),
        ]);


        return redirect()->route('brands.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(Brand $brand)
    {
        return view('admin.brands.show',[
        $brand=>'brand']);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Brand $brand)
    {
        return view('admin.brands.edit',[
            $brand=>'brand']);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Brand $brand)
    {

        $requestData =[

            'brand_name'=>$request->brand_name,
            'brand_slug'=>strtolower(str_replace('','_',$request->brand_name)),
            'brand_image'=> $this->uploadImage(request()->file('brand_image')),

        ];

        if($request->hasFile('brand_image')){
            $requestData['brand_image']=$this->uploadImage(request())->file('brand_image');
        }
        $brand->update($requestData);

        $brand->update([

        ]);
        return redirect()->route('brands.index');

    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Brand $brand)
    {
        $brand->delete();

        return redirect()->route('brands.index');

    }

    public function uploadImage($file)
    {

        $fileName = time().'.'.$file->getClientOriginalExtension();
        Image::make($file)
            ->resize(300,200)
            ->save(storage_path().'/app/public/brand/'.$fileName);
        return $fileName;

    }

}

resources/views/admin/brands/create.blade.php
<x-admin.layouts.admin_master>

    <div class="container-fluid p-0">

        <form action="{{ route('brands.store') }}" method="post" enctype="multipart/form-data">
            @csrf
            <div class="mb-3 row">
                <label for="inputTitle" class="col-sm-3 col-form-label">Brand</label>
                <div class="col-sm-9">
                    <input
                        type="text"
                        class="form-control"
                        id="inputTitle"
                        name="brand_name"
                        value="">
                    @error('brand_name')
                    <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
            </div>


           



            <div class="mb-3 row">
                <label for="inputImg" class="col-sm-3 col-form-label">Image</label>
                <div class="col-sm-9">
                    <input
                        type="file"
                        class="form-control"
                        id="inputImg"
                        name="brand_image"
                        value=""
                    >
                    @error('brand_image')
                    <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>

            </div>


            <div class="mb-3 row">
                <div class="col-sm-9 offset-3">
                    <button type="submit" class="btn btn-info">Submit</button>
                </div>

            </div>

        </form>
    </div>

</x-admin.layouts.admin_master>

resources/views/admin/brands/edit.blade.php
<x-admin.layouts.admin_master>

    <div class="container-fluid p-0">

        <form action="{{ route('brands.update',['brand'=>$brand->id]) }}" method="post" enctype="multipart/form-data">
            @csrf
            @method('patch')
            <div class="mb-3 row">
                <label for="inputTitle" class="col-sm-3 col-form-label">brand</label>
                <div class="col-sm-9">
                    <input
                        type="text"
                        class="form-control"
                        id="inputTitle"
                        name="brand_name"
                        value="{{old('brand_name',$brand->brand_name)}}">
                                        @error('brand_name')
                                        <p class="text-danger">{{ $message }}</p>
                                        @enderror
                </div>
            </div>


            <div class="mb-3 row">
                <label for="inputdetails" class="col-sm-3 col-form-label">Details</label>
                <div class="col-sm-9">
                    <input
                        type="text"
                        class="form-control"
                        id="inputdetails"
                        name="brand_slug"
                        value="{{old('brand_slug',$brand->brand_slug)}}">
                                        @error('brand_slug')
                                        <p class="text-danger">{{ $message }}</p>
                                        @enderror
                </div>
            </div>

            <div class="mb-3 row">
                <label for="inputImg" class="col-sm-3 col-form-label">Image</label>
                <div class="col-sm-9">
                    <input
                        type="file"
                        class="form-control"
                        id="inputImg"
                        name="brand_image"
                        value="{{old('brand_image',$brand->brand_image)}}">
                                        @error('brand_image')
                                        <p class="text-danger">{{ $message }}</p>
                                        @enderror
                </div>

            </div>


            <div class="mb-3 row">
                <div class="col-sm-9 offset-3">
                    <button type="submit" class="btn btn-info">update</button>
                </div>

            </div>

        </form>
    </div>

</x-admin.layouts.admin_master>

resources/views/admin/brands/index.blade.php
<x-admin.layouts.admin_master>
    <div class="col-12 col-lg-11 col-xxl-9 d-flex">
        <div class="card flex-fill">
            <div class="card-header">

                <div class="row">
                    <div class="col-lg-12 margin-tb">
                        <div class="pull-left">
                            <h2> create brand</h2>
                        </div>
                        <div class="pull-right">
                            <a class="btn btn-primary" href="{{ route('brands.create') }}"> Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-body">
                @if (session('message'))
                    <div class=" alert alert-success">
                        <span class="close" data-dismiss="alert"> </span>
                        <strong>{{ session('message') }}</strong>
                    </div>
                @endif

            <table class="table table-hover my-0">
                <thead>
                <tr>
                    <th>SL</th>
                    <th class="d-none d-xl-table-cell">Title</th>
                    <th class="d-none d-xl-table-cell">image</th>
                    <th class="d-none d-md-table-cell">Action</th>
                </tr>
                </thead>
                <tbody>
    @foreach($brands as $key => $brand)
        <tr>
            <td> {{ $key+1 }} </td>
            <td>{{ $brand->brand_name }}</td>
            <td> <img src="/storage/brand/{{ ($brand->brand_image) }}" style="width: 70px; height:40px;" >  </td>
            
            <td>
                <a class="btn btn-info btn-sm"
                   href="{{ route('brands.show', ['brand' => $brand->id]) }}">Show</a>
                <a class="btn btn-info btn-sm"
                   href="{{ route('brands.edit', ['brand' => $brand->id]) }}">Edit</a>
                <form style="display:inline"
                      action="{{ route('brands.destroy',['brand' => $brand->id]) }}"
                      method="post">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger btn-sm"
                            onclick="return confirm('are sure want delete?')">Delete</button>
                </form>

            </td>
        </tr>

    @endforeach
                </tbody>
            </table>

            </div>
        </div>
    </div>
</x-admin.layouts.admin_master>

resources/views/admin/brands/show.blade.php
<x-admin.layouts.admin_master>

    <div class="container-fluid p-0">
        <div class="row">
            <div class="col-lg-12 margin-tb">
                <div class="pull-left">
                    <h2> Show brand</h2>
                </div>
                <div class="pull-right">
                    <a class="btn btn-primary" href="{{ route('brands.index') }}"> Back</a>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    {{ $brand->brand_name }}
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Details:</strong>
                    {{ $brand->brand_slug }}
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Image:</strong>
                    <img src="{{ asset($brand->brand_image) }}" style="width: 70px; height:40px;" >
                </div>
            </div>
        </div>

    </div>

</x-admin.layouts.admin_master>